### PR TITLE
Add a new function to help print out Diff3 merge

### PR DESCRIPTION
**Pull request by blacksteed232**
This aims to create a function like `merge` but for `diff3` which is similar to [git-diff3](https://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging) format where you show the common ancestor/original as well.
I also corrected the type definitions to make this more convenient for `Typescript` users

@bhousel regarding #38, if you're good with this PR, can you do a release?

Again, thank you so much for this great library!

### CODE REVIEW

**Comment by blacksteed232** [comment]
@bhousel just want to check if you had time to take a look at this. Also if the naming of the function (i.e. `mergeDiff3`) is not great, let me know if you have any suggestions. Thanks!

**Comment by bhousel** [comment]
> just want to check if you had time to take a look at this.

Sorry, i keep forgetting, I'll try to review this week 👍

**Comment by blacksteed232** [comment]
@bhousel Thank you so much!

**Comment by bhousel** [comment]
Thanks @blacksteed232 it looks useful.. I agree the name of the function is kind of confusing, but I dont have any strong opinions about it, so I'm happy to just merge as-is and do a release.

**Comment by blacksteed232** [comment]
Thanks @bhousel! Please let me know when you release this.

_Also just one small recommendation: this library is super useful and I feel like it's underrated. I was looking for a library that can do something similar to `git-diff` (especially 3-way merge) and it took me a while to find this gem of yours. Maybe it would be useful to add more tags/keywords to the project on Github and NPM._

**Comment by bhousel** [comment]
> Thanks @bhousel! Please let me know when you release this.

seconds ago!


> Also just one small recommendation: this library is super useful and I feel like it's underrated. I was looking for a library that can do something similar to `git-diff` (especially 3-way merge) and it took me a while to find this gem of yours. Maybe it would be useful to add more tags/keywords to the project on Github and NPM.

Thanks! I'm really happy you found it helpful.  We use this library in the [OpenStreetMap iD editor](https://github.com/openstreetmap/iD) for conflict resolution. I was also surprised to find that there aren't a lot of Diff3 solutions for JavaScript.  I'll add some more keywords 👍

**Pull request merged**
